Repository ForgeFlow/stock-rma, pull requests merged in 2019-11, with the labels that each got.

#118 [11.0][FIX] Pump version numbers to 11.0
  rma_account_analytic/__manifest__.py
  rma_analytic/__manifest__.py
  rma_operating_unit/__manifest__.py
  rma_purchase_analytic/__manifest__.py
  rma_sale_analytic/__manifest__.py
Labels: Ready to merge, fastracking, migration

#117 [12.0][MIG] rma_purchase_analytic
  rma_purchase_analytic/README.rst
  rma_purchase_analytic/__init__.py
  rma_purchase_analytic/__manifest__.py
  rma_purchase_analytic/models/__init__.py
  rma_purchase_analytic/models/purchase_order_line.py
  rma_purchase_analytic/wizards/__init__.py
  rma_purchase_analytic/wizards/rma_add_purchase.py
Labels: Needs review, Ready to merge

#116 [12.0][MIG] rma_sale_analytic
  rma_sale_analytic/README.rst
  rma_sale_analytic/__init__.py
  rma_sale_analytic/__manifest__.py
  rma_sale_analytic/models/__init__.py
  rma_sale_analytic/models/sale_order_line.py
  rma_sale_analytic/wizards/__init__.py
  rma_sale_analytic/wizards/rma_add_sale.py
  rma_sale_analytic/wizards/rma_order_line_make_sale_order.py
Labels: Needs review, Ready to merge

#63 [12.0] [MIG] rma_operating_unit
  oca_dependencies.txt
  rma_operating_unit/README.rst
  rma_operating_unit/__init__.py
  rma_operating_unit/__manifest__.py
  rma_operating_unit/models/__init__.py
  rma_operating_unit/models/rma_order.py
  rma_operating_unit/models/rma_order_line.py
  rma_operating_unit/security/rma_security.xml
  rma_operating_unit/tests/__init__.py
  rma_operating_unit/tests/test_rma_operating_unit.py
  rma_operating_unit/views/rma_order_line_view.xml
  rma_operating_unit/views/rma_order_view.xml
  rma_operating_unit/wizards/rma_add_stock_move.py
Labels: Needs review, migration

#120 [12.0][MIG] rma_purchase_operating_unit
  rma_purchase_operating_unit/README.rst
  rma_purchase_operating_unit/__init__.py
  rma_purchase_operating_unit/__manifest__.py
  rma_purchase_operating_unit/wizards/__init__.py
  rma_purchase_operating_unit/wizards/rma_line_make_purchase_order.py
Labels: Needs review, migration
